In [1]:
# Load necessary libs and set seed
set.seed(1234)

library(tidyverse)
library(tidymodels)
library(repr)
library(gridExtra)
library(faraway)
library(mltools)
library(leaps)
library(glmnet)
library(cowplot)
library(MASS)
library(boot)
library(caret)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
── Attaching packages ────────────────────────────────────── tidymodels 1.1.1 ──

✔ broom        1.0.5     ✔ rsample      1.2.0
✔ dials        1.2.0     ✔ tune         1.1.2
✔ infer        1.0.5     ✔ workflows    1.1.3
✔ modeldata    1.2.0     ✔ workflowsets 1.0.1
✔ parsnip      1.1.1     ✔ yardstick    1.2.0
✔ recipes      1.0.8

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use tidymodels_prefer() to resolve common conflicts.


Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine



Attaching package: ‘mltools’


The following objects are masked from ‘package:yardstick’:

    mcc, rmse


The following object is masked from ‘package:tidyr’:

    replace_na


Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loaded glmnet 4.1-8


Attaching package: ‘cowplot’


The following object is masked from ‘package:lubridate’:

    stamp



Attaching package: ‘MASS’


The following object is masked from ‘package:dplyr’:

    select



Attaching package: ‘boot’


The following objects are masked from ‘package:faraway’:

    logit, melanoma


Loading required package: lattice


Attaching package: ‘lattice’


The following object is masked from ‘package:boot’:

    melanoma


The following object is masked from ‘package:faraway’:

    melanoma



Attaching package: ‘caret’


The following objects are masked from ‘package:yardstick’:

    precision, recall, sensitivity, specificity


The following object is masked from ‘package:purrr’:

    lift

# Introduction

We plan on using the 'Adult' dataset (https://archive.ics.uci.edu/dataset/2/adult) from the UC Irvine Machine Learning Repository. The 'Adult' dataset was extracted from the 1994 Census Bureau database and compiled by Ronny Kohavi and Barry Becker. The dataset contains general identification information on the average adult about their personal and work lives. Our adult dataset consists of 48,842 instances or observations. If records with unknown values are removed, it contains 45,222 observations. With an abundance of data to work with, our primary goal is to target the 'income’ variable which is a binary attribute that classifies individuals into two categories: those who earn less than or equal to 50000 dollars (<=50K) and those who earn more than $50,000 (>50K) and be able to make accurate predictions about it. To begin, allow us to describe the variables we’ll be working with in the following overview about the variable:

| Feature         | Description |
|:----------------|:------------|
| `age`           | A continuous feature representing the age of the individual in years. |
| `workclass`     | A categorical feature categorizing individuals into employment categories such as Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked. This variable contains missing values. |
| `fnlwgt`        | A continuous attribute that estimates the number of people in the population with the same demographics as the individual. |
| `education`     | A categorical feature indicating the highest level of education completed by the individual, with options like Bachelors, Some-college, 11th, HS-grad, and more. |
| `education_num` | A numeric representation (continuous) of the highest education level completed by the individual, ranging from 1 to 16. |
| `marital_status`| A categorical feature denoting the marital status of the individual, with options like Married-civ-spouse, Divorced, Never-married, and more. |
| `occupation`    | A categorical feature representing the job of the individual. Occupation categories include Tech-support, Craft-repair, and others. This variable also contains missing values. |
| `relationship`  | A categorical feature describing the individual's relationship status, with categories like Wife, Own-child, Husband, and more. |
| `race`          | A categorical attribute indicating the individual's race, with options like White, Asian-Pac-Islander, and others. |
| `sex`           | A binary attribute classifying the individual's gender as either male or female. |
| `capital_gain`  | A continuous attribute representing the capital gain in the previous year. |
| `capital_loss`  | A continuous attribute representing the capital loss in the previous year. |
| `hours_per_week`| A continuous attribute indicating the number of hours worked per week by the individual. |
| `native_country`| A categorical feature specifying the native country of the individual, with categories including the United-States, Cambodia, England, and more. This variable also contains missing values. |
| `income`        | A binary attribute that encodes whether the individual earns <=50K or >50K dollars. |


Generally speaking, we want to answer the following question: "which condition factors, when used as explanatory variables, create the model that yields the most accurate real-time predictions of annual income in North America?" We intend to utilize the dataset to develop a predictive model that can forecast an individual's income level (the binary response variable) by taking necessary factors into account. The goal is to use the available data to create a predictive tool that can estimate whether an individual earns less than or equal to 50,000 dollars or more than $50,000 annually. Given that the response variable 'income' is binary, logistic regression appears to be a suitable technique for this prediction task. Logistic regression is a powerful technique which gives us the ability to determine the probability of a binary outcome (in this case, earning more or less/equal to 50k) given other input variables. The dataset contains a wealth of information on these variables, which will be instrumental in constructing and training an accurate logistic regression model. 


The distribution of income has been a significant focus in economic and social research. Studies have explored various factors influencing an individual's earning potential, contributing valuable insights into societal trends and disparities. The paper by Harmon, Oosterbeek, and Walker (2003) titled "The Returns to Education: Microeconomics"  is a pivotal contribution to understanding the relationship between education and income levels. This paper extensively investigates the economic aspects of education by focusing on the returns individuals receive from investing in education.
By analyzing the relationships and patterns within the variables in our dataset, we aim to make informed predictions about an individual's income level. Furthermore, Hegewisch and Hartmann’s paper on gender wage gap sheds light on the persistence of occupational gender segregation in the labor market. It highlights the stagnation in integrating occupations across various demographics, including different generations, educational levels, and racial and ethnic groups, particularly over the past decade. There are many other researches that discuss the influence of various factors on income. We want to examine what combination of factors are the most influential in terms of determining an individual’s earning potential. It can have applications in diverse fields, such as human resources, financial planning, and public policy.

To begin, we will first read our dataset into R and perform general cleaning and wrangling to make the analysis easier.

# Methods and Results

## Cleaning and Wrangling Data

In order to enhance the quality and clarity of our data analysis, we will begin by assigning meaningful column names to our variables. This practice not only helps us maintain data integrity but also makes the subsequent analysis more accessible and interpretable.Our analysis is primarily centered around choosing variables that are the most statistically significant in predicting income levels.Furthermore, to ensure the reliability of our analysis, we will filter out any records with missing values in the 'income,' ‘workclass,’ and ‘occupation’ column. This step ensures that our results are based on complete and accurate data. Regarding the choice between 'education_num' and 'education,' we opt for 'education_num' due to its numerical representation of education levels. This numeric format is advantageous for statistical modeling, as it can capture ordinal relationships and lead to more straightforward analyses. In contrast, 'education' exhibits a significantly higher cardinality, which can result in longer processing times and potentially complicate the analysis. Furthermore, we also dropped the country column because it is a redundant variable in describing ethnicity and we already use race to do this. It's important to note that the exclusion of other variables is deliberate. We hope to gain insights into what variables have the most statistically significant impact in determining the income level.

In [2]:
#Read and tidy data
adult_test <- read.table("https://github.com/Haobo11/STAT301-Group-Project/raw/main/adult.test",  sep = "," , skip=1)
colnames(adult_test) <- c("age", "workclass", "fnlwgt", "education", "education_num", "marital_status",
                          "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss",
                          "hours_per_week", "native_country", "income")
adult_test <- adult_test|>
    dplyr::select(- capital_gain, - capital_loss, - education_num)|> #Remove the capital_gain and capital_loss column, 
                                                 #since there are many missing value in thest two variable.
    mutate(workclass = factor(workclass), #Factor the categorical variable
           education = factor(education),
           marital_status = factor(marital_status),
           occupation = factor(occupation),
           relationship = factor(relationship),
           race = factor(race),
           sex = factor(sex),
           native_country = factor(native_country),
           income = factor(income))|>
    mutate(across(where(is.character), str_trim))|>
    filter(occupation!=" ?")|>
    filter(native_country!=" ?")|> #Filter the observation that have missing value
    filter(native_country == c(" United-States", " Canada", " Mexico", " Jamaica", " Cuba"))#Since our quetion focused on the data in North America, 
                                                                                             # we filter the North America Country in Dataset.
head(adult_test)

adult_data <- read.table("https://github.com/Haobo11/STAT301-Group-Project/raw/main/adult.data",  sep = ",")
colnames(adult_data) <- c("age", "workclass", "fnlwgt", "education", "education_num", "marital_status",
                          "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss",
                          "hours_per_week", "native_country", "income")
adult_data <- adult_data|>
     dplyr::select(- capital_gain, - capital_loss,  - education_num)|> #Remove the capital_gain and capital_loss column, 
                                                 #since there are many missing value in thest two variable.
    mutate(workclass = factor(workclass),#Factor the categorical variable
           education = factor(education),
           marital_status = factor(marital_status),
           occupation = factor(occupation),
           relationship = factor(relationship),
           race = factor(race),
           sex = factor(sex),
           native_country = factor(native_country),
           income = factor(income))|>
    filter(occupation!=" ?") |>
    filter(native_country!=" ?")|> #Filter the observation that have missing value
    filter(native_country == c(" United-States", " Canada", " Mexico", " Jamaica", " Cuba")) #Since our quetion focused on the data in North America, 
                                                                                             # we filter the North America Country in Dataset.
head(adult_data)

  age workclass         fnlwgt education     marital_status
1 25   Private          226802  11th          Never-married
2 63   Self-emp-not-inc 104626  Prof-school   Married-civ-spouse
3 26   Private           82091  HS-grad       Never-married
4 37   Private           60548  HS-grad       Widowed
5 45   Self-emp-not-inc 432824  HS-grad       Married-civ-spouse
6 46   State-gov        106444  Some-college  Married-civ-spouse
  occupation         relationship   race   sex     hours_per_week
1  Machine-op-inspct  Own-child      Black  Male   40
2  Prof-specialty     Husband        White  Male   32
3  Adm-clerical       Not-in-family  White  Female 39
4  Machine-op-inspct  Unmarried      White  Female 20
5  Craft-repair       Husband        White  Male   90
6  Exec-managerial    Husband        Black  Male   38
  native_country income
1  United-States  <=50K.
2  United-States  >50K.
3  United-States  <=50K.
4  United-States  <=50K.
5  United-States  >50K.
6  United-States  >50K.

Warning message:
“There were 2 warnings in `filter()`.
The first warning was:
ℹ In argument: `==...`.
Caused by warning in `==.default`:
! longer object length is not a multiple of shorter object length
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.”

  age workclass         fnlwgt education     marital_status
1 39   State-gov         77516  Bachelors     Never-married
2 28   Private          338409  Bachelors     Married-civ-spouse
3 37   Private          284582  Masters       Married-civ-spouse
4 37   Private          280464  Some-college  Married-civ-spouse
5 25   Self-emp-not-inc 176756  HS-grad       Never-married
6 54   Private          302146  HS-grad       Separated
  occupation       relationship   race   sex     hours_per_week native_country
1  Adm-clerical     Not-in-family  White  Male   40              United-States
2  Prof-specialty   Wife           Black  Female 40              Cuba
3  Exec-managerial  Wife           White  Female 40              United-States
4  Exec-managerial  Husband        Black  Male   80              United-States
5  Farming-fishing  Own-child      White  Male   35              United-States
6  Other-service    Unmarried      Black  Female 20              United-States
  income
1  <=50K
2  <=50K
3  <=50K
4  >50K
5  <=50K
6  <=50K

In [ ]:
# Assuming adult_data is our training dataset and adult_test is our testing dataset
adult_data <-
  adult_data %>%
  mutate(income = ifelse(income == ">50K", 1, 0))
head(adult_data)

adult_test <-
  adult_test %>%
  mutate(income = ifelse(income == ">50K.", 1, 0))
head(adult_test)

# Fitting the logistic regression model with stepwise selection using BIC
full_model <- glm(income ~ ., data = adult_data, family = binomial())
full_model_result <- tidy(full_model)
full_model_result
stepwise_model <- stepAIC(full_model, direction = "both", trace = FALSE, k = log(nrow(adult_data)))
full_model_result

# Summarizing the model
summary(stepwise_model)

# Predicting and evaluating on the test set
predictions <- round(predict(stepwise_model, newdata = adult_test, type = "response"),0)

# Use the confusionMatrix function from the caret package
adult_income_confusion_matrix <-
  confusionMatrix(
    data = as.factor(predictions),
    reference = as.factor(adult_test$income),
    positive = "1"
  )
adult_income_confusion_matrix

  age workclass         fnlwgt education     marital_status
1 39   State-gov         77516  Bachelors     Never-married
2 28   Private          338409  Bachelors     Married-civ-spouse
3 37   Private          284582  Masters       Married-civ-spouse
4 37   Private          280464  Some-college  Married-civ-spouse
5 25   Self-emp-not-inc 176756  HS-grad       Never-married
6 54   Private          302146  HS-grad       Separated
  occupation       relationship   race   sex     hours_per_week native_country
1  Adm-clerical     Not-in-family  White  Male   40              United-States
2  Prof-specialty   Wife           Black  Female 40              Cuba
3  Exec-managerial  Wife           White  Female 40              United-States
4  Exec-managerial  Husband        Black  Male   80              United-States
5  Farming-fishing  Own-child      White  Male   35              United-States
6  Other-service    Unmarried      Black  Female 20              United-States
  income
1 0
2 0
3 0
4 0
5 0
6 0

  age workclass         fnlwgt education     marital_status
1 25   Private          226802  11th          Never-married
2 63   Self-emp-not-inc 104626  Prof-school   Married-civ-spouse
3 26   Private           82091  HS-grad       Never-married
4 37   Private           60548  HS-grad       Widowed
5 45   Self-emp-not-inc 432824  HS-grad       Married-civ-spouse
6 46   State-gov        106444  Some-college  Married-civ-spouse
  occupation         relationship   race   sex     hours_per_week
1  Machine-op-inspct  Own-child      Black  Male   40
2  Prof-specialty     Husband        White  Male   32
3  Adm-clerical       Not-in-family  White  Female 39
4  Machine-op-inspct  Unmarried      White  Female 20
5  Craft-repair       Husband        White  Male   90
6  Exec-managerial    Husband        Black  Male   38
  native_country income
1  United-States 0
2  United-States 0
3  United-States 0
4  United-States 0
5  United-States 0
6  United-States 0

Warning message:
“glm.fit: algorithm did not converge”

   term                                 estimate      std.error
1  (Intercept)                          -2.656607e+01 1.250176e+05
2  age                                  -1.313071e-16 4.637601e+02
3  workclass Local-gov                  -5.201738e-15 3.238467e+04
4  workclass Private                    -2.682446e-15 2.724923e+04
5  workclass Self-emp-inc               -2.627091e-15 3.660098e+04
6  workclass Self-emp-not-inc           -2.755156e-15 3.195502e+04
7  workclass State-gov                  -4.881199e-14 3.465759e+04
8  workclass Without-pay                -8.709984e-15 1.494257e+05
9  fnlwgt                                1.904896e-20 4.580394e-02
10 education 11th                       -1.233601e-16 3.859415e+04
11 education 12th                        2.918447e-15 5.164119e+04
12 education 1st-4th                     3.685420e-16 8.804507e+04
13 education 5th-6th                     3.892460e-15 6.745522e+04
14 education 7th-8th                     7.017875e-15 4.503695e+04
15 education 9th                         3.362066e-15 5.170515e+04
16 education Assoc-acdm                  2.865914e-15 4.069660e+04
17 education Assoc-voc                  -2.440733e-16 3.797942e+04
18 education Bachelors                  -1.088099e-14 3.292526e+04
19 education Doctorate                   9.662661e-15 5.625562e+04
20 education HS-grad                     3.308036e-15 3.080218e+04
21 education Masters                     5.102885e-16 3.797568e+04
22 education Preschool                   1.003086e-14 1.398604e+05
23 education Prof-school                -2.715065e-15 5.059297e+04
24 education Some-college                2.819919e-15 3.142407e+04
25 marital_status Married-AF-spouse     -2.371562e-15 1.304660e+05
26 marital_status Married-civ-spouse    -2.294098e-15 6.490299e+04
27 marital_status Married-spouse-absent -2.850573e-15 5.044785e+04
28 marital_status Never-married         -1.516347e-14 1.770982e+04
29 marital_status Separated             -2.602362e-15 2.942942e+04
30 marital_status Widowed                5.406302e-16 3.364248e+04
31 occupation Armed-Forces               1.481630e-14 2.079389e+05
32 occupation Craft-repair               1.604357e-14 2.075792e+04
33 occupation Exec-managerial            1.859862e-14 1.981493e+04
34 occupation Farming-fishing            1.515450e-14 3.122778e+04
35 occupation Handlers-cleaners          1.613171e-14 2.805861e+04
36 occupation Machine-op-inspct          1.292529e-14 2.410617e+04
37 occupation Other-service              1.645766e-14 2.059432e+04
38 occupation Priv-house-serv            7.908487e-15 8.396071e+04
39 occupation Prof-specialty             2.744931e-14 2.162141e+04
40 occupation Protective-serv            2.701811e-14 3.640920e+04
41 occupation Sales                      1.606477e-14 2.023585e+04
42 occupation Tech-support               2.200595e-14 3.045588e+04
43 occupation Transport-moving           1.914287e-14 2.604859e+04
44 relationship Not-in-family           -7.897969e-15 6.445737e+04
45 relationship Other-relative          -2.774042e-15 6.550051e+04
46 relationship Own-child                5.277699e-17 6.406680e+04
47 relationship Unmarried               -5.087170e-15 6.658928e+04
48 relationship Wife                    -8.271968e-15 2.693954e+04
49 race Asian-Pac-Islander               6.236104e-15 7.138444e+04
50 race Black                            2.891996e-15 5.192984e+04
51 race Other                            3.285563e-15 7.775828e+04
52 race White                           -2.505081e-16 4.953844e+04
53 sex Male                             -1.443966e-14 1.431752e+04
54 hours_per_week                        9.964652e-18 4.396485e+02
55 native_country Cuba                  -6.709404e-17 1.164571e+05
56 native_country Jamaica               -2.877072e-15 1.207411e+05
57 native_country Mexico                -3.252411e-16 8.858354e+04
58 native_country United-States         -5.839918e-16 8.004893e+04
   statistic     p.value
1  -2.124986e-04 0.9998305
2  -2.831358e-19 1.0000000
3  -1.606235e-19 1.0000000
4  -9.844117e-20 1.0000000
5  -7.177653e-20 1.0000000
6  -8.621982e-20 1.0000000
7  -1.408407e-18 1.0000000
8  -5.828975e-20 1.0000000
9   4.158804e-19 1.0000000
10 -3.196340e-21 1.0000000
11  5.651395e-20 1.0000000
12  4.185834e-21 1.0000000
13  5.770435e-20 1.0000000
14  1.558248e-19 1.0000000
15  6.502381e-20 1.0000000
16  7.042146e-20 1.0000000
17 -6.426462e-21 1.0000000
18 -3.304754e-19 1.0000000
19  1.717635e-19 1.0000000
20  1.073962e-19 1.0000000
21  1.343724e-20 1.0000000
22  7.172048e-20 1.0000000
23 -5.366488e-20 1.0000000
24  8.973757e-20 1.0000000
25 -1.817763e-20 1.0000000
26 -3.534658e-20 1.0000000
27 -5.650533e-20 1.0000000
28 -8.562180e-19 1.0000000
29 -8.842723e-20 1.0000000
30  1.606987e-20 1.0000000
31  7.125313e-20 1.0000000
32  7.728889e-19 1.0000000
33  9.386164e-19 1.0000000
34  4.852890e-19 1.0000000
35  5.749291e-19 1.0000000
36  5.361818e-19 1.0000000
37  7.991362e-19 1.0000000
38  9.419271e-20 1.0000000
39  1.269543e-18 1.0000000
40  7.420682e-19 1.0000000
41  7.938764e-19 1.0000000
42  7.225519e-19 1.0000000
43  7.348909e-19 1.0000000
44 -1.225301e-19 1.0000000
45 -4.235145e-20 1.0000000
46  8.237807e-22 1.0000000
47 -7.639624e-20 1.0000000
48 -3.070568e-19 1.0000000
49  8.735943e-20 1.0000000
50  5.569045e-20 1.0000000
51  4.225354e-20 1.0000000
52 -5.056842e-21 1.0000000
53 -1.008531e-18 1.0000000
54  2.266504e-20 1.0000000
55 -5.761266e-22 1.0000000
56 -2.382845e-20 1.0000000
57 -3.671575e-21 1.0000000
58 -7.295435e-21 1.0000000

Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”
Warning message:
“glm.fit: algorithm did not converge”

## Methods: Plan

### Explanation of Code
To quickly summarize, in our experiment, we first used variable selection techniques such as stepwise selection to first obtain the variables which have the highest probability of giving us higher accuracy. Then, after determining the best possible selection of variables, we fit the model on our test set and interpret our results using a confusion matrix to determine the amount of times we receive true positives, true negatives, and times where we get the incorrect answers. 

### Why Stepwise Selection?
In our model, we decided to use a stepwise selection model to help us pick out the most relevant variables in our dataset. Stepwise selection simplifies the model-building process by automating the selection of significant variables, which is particularly useful when there are many potential predictors and no clear indication of the most important ones. By combining both forward and backward selection methods, it adds variables that provide a significant contribution to the model and removes those that do not. The end result is a model which contains variables that have a justifiable impact on the response variable and leads us to a model that balances both complexity and performance
Interpretation

The logistic regression model demonstrates a good level of accuracy (82.56%) in predicting adult annual income in North America, indicating its effectiveness in distinguishing between income levels. However, the moderate Kappa value (0.5112) suggests only moderate agreement beyond chance, and the difference between sensitivity (56.28%) and specificity (91.60%) highlights a potential bias towards predicting lower income levels more accurately. These results suggest the model's utility in addressing the research question but also point towards the need for further refinement, possibly by re-evaluating variable selection or employing techniques like ROC curve analysis to adjust decision thresholds for better balance in predictive performance. Incorporating cross-validation could enhance model robustness and generalization, reducing the risk of overfitting and providing a more balanced prediction for both income classes.

### For lasso:
first, we split the data into a 75/25 train/test split to test the final model with the optimal lambda value obtained from cross validation. We also converted the string response into binary values as that is what glmnet expects as the response for logistic regression. Then we performed lasso cross validation to find the optimal and 1 standard error lambda values. Using the 1 standard error lambda value, we test the fitted model on the training dataset. The 1 standard error lambda value was used in order to have a more conservative model in terms of coefficient shrinkage, as lasso tends to overshrink the coefficients. Cross validation using deviance loss as the loss function of choice allows us to estimate the performance of the model on unseen (test) data, without any strong assumptions. Lasso was used as it allows for both regularization (allowing the model to hopefully generalize better to unseen data), as well as performing variable selection via coordinate descent, as opposed to ridge. An alternative would be elastic net, which combines benefits of ridge (when many predictors are significant, and negates some multicollinearity issues) along with lasso (variable selection).

The final model achieves a good level of accuracy (84.69%) in predicting adult annual income in north america, however it also has the same issues as the model obtained from subset selection, with a kappa level of only 0.5508, which indicates it has better agreement beyond chance than the subset selection model, however still only by a small amount. There is also a large difference between sensitivity and specificity (57.26%, 93.56%), indicating that this model is a better classifier for negative values (incomes below 50k). This may be a result of the disproportionate group sizes of positive vs negative values, which is simply a result of reality as the more people within the population earn less than 50k a year as opposed to more. 

# Discussion

Based on our previous discussion in the paragraph above, we can conclude that our logistic regression model is effective in predicting whether or not a given individual will earn more than $50,000 annually, or less than or equal to that. 

Based on our results, this is about what we expected. Using various statistical techniques on a dataset which has information that is relevant to the response variable, we expected to obtain a predictive model that yielded a decent to good accuracy. 
 
Based on the predicted accuracy of our two methods the Lasso regression method results in a higher overall accuracy (84.69%) compared to the stepwise selection method (82.56%). The Kappa statistic, which measures agreement beyond chance, is also higher in the Lasso model, indicating a better performance in classification tasks. In terms of sensitivity, which is the true positive rate, the Lasso model is slightly more capable of correctly identifying those who earn more than $50,000. This is complemented by a higher specificity rate, which indicates that the Lasso model is better at correctly identifying those who do not exceed the income threshold.

In the future, an improvement for our model could be to incorporate other techniques such as cross-validation to ensure we pick a good training and validation set before fitting the model onto our test set. 

All in all, we believe our findings were successful as our predictive model was able to accurately make predictions on income levels based on the given explanatory variables. As mentioned above, our findings would be useful in helping predict the income potential of an individual based on their background, and can be applied in a tremendous number of fields such as developing marketing strategies, real estate planning, and many more.

# References

Becker, Barry and Kohavi,Ronny. (1996). Adult. UCI Machine Learning Repository. https://doi.org/10.24432/C5XW20
Harmon, C., Oosterbeek, H., & Walker, I. (2003). The returns to education: Microeconomics. Journal of Economic Surveys, 17(2), 115–156. https://doi.org/10.1111/1467-6419.00191 
Hegewisch, A., & Hartmann, H. (2014). Occupational segregation and the gender wage gap: A job half done. PsycEXTRA Dataset. https://doi.org/10.1037/e529142014-001